config/routes.rb
HerokuManager::Application.routes.draw do
  resources :accounts do
    resources :apps
  end

  root :to => 'accounts#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :email, :password
  validates_presence_of :email, :password
  
  def apps
    Heroku::Client.new(email, password).list
  end
  
  def destroy_app(app)
    Heroku::Client.new(email, password).destroy(app)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(params[:account])
    if @account.save
      redirect_to @account, :notice => "Successfully created account."
    else
      render :action => 'new'
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(params[:account])
      redirect_to @account, :notice  => "Successfully updated account."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to accounts_url, :notice => "Successfully destroyed account."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def destroy
    account = Account.find(params[:account_id])
    account.destroy_app(params[:id])
    redirect_to account_path(account), :notice => "Destroyed #{params[:id]}"
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/accounts/_form.html.erb
<%= form_for @account do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/accounts/edit.html.erb
<% title "Edit Account" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @account %> |
  <%= link_to "View All", accounts_path %>
</p>

app/views/accounts/index.html.erb
<% title "Accounts" %>

<table>
  <tr>
    <th>Email</th>
  </tr>
  <% for account in @accounts %>
    <tr>
      <td><%= account.email %></td>
      <td><%= link_to "Show", account %></td>
      <td><%= link_to "Edit", edit_account_path(account) %></td>
      <td><%= link_to "Destroy", account, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Account", new_account_path %></p>

app/views/accounts/new.html.erb
<% title "New Account" %>

<%= render 'form' %>

<p><%= link_to "Back to List", accounts_path %></p>

app/views/accounts/show.html.erb
<% title "Account" %>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <%= link_to "Edit", edit_account_path(@account) %> |
  <%= link_to "Destroy", @account, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", accounts_path %>
</p>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Owner</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<% for app in @account.apps %>
	<tr>
		<td><%= app[0] %></td>
		<td><%= app[1] %></td>
		<td><%= button_to "Delete", account_app_path(@account.id, app[0]), :method => :delete %></td>
	</tr>
	<% end %>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>